name: Notification Teams and Email

on:
  repository_dispatch:
    types: [notify_teams]   # Trigger on the notify_team event_type of the payload from the Handle_Publish_Notification workflow.

jobs:
  notify_teams_channel:
    runs-on: ubuntu-latest

    steps:
      - name: Send Notification on Teams Channel
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          curl -H 'Content-Type: application/json' -d '{
            "title": "${{github.event.client_payload.title}}",
            "text": "From the new model : ${{github.event.client_payload.text}}",
            "themeColor": "FF0000"
          }' $TEAMS_WEBHOOK_URL
