name: Detect and Handle Merge Conflicts

on:
  pull_request:
    types: [opened, synchronize]  # Trigger on PR creation and update
    branches:
      - sit

jobs:
  check_merge_conflict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}

      - name: Attempt to merge base branch
        id: merge
        run: |
          git merge --no-commit --no-ff origin/${{ github.base_ref }} || true
          
      - name: Check for merge conflicts
        id: check_conflict
        run: |
          CONFLICTS=$(git ls-files -u | wc -l)
          if [ "$CONFLICTS" -gt 0 ] ; then
            echo "Merge conflict detected"
            echo "::set-output name=conflict::true"
          else
            echo "No merge conflicts detected"
            echo "::set-output name=conflict::false"
          fi

      - name: Send notification on merge conflict
        if: steps.check_conflict.outputs.conflict == 'true'
        run: |
          echo "Notify about the conflict or handle it accordingly."
