name: Create Release Branch and PRs

on:
  workflow_dispatch:
    inputs:
      user-story-id:
        description: 'User Story Identifier'
        required: true

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create release branch
        run: |
          USER_STORY_ID=${{ github.event.inputs['user-story-id'] }}
          RELEASE_BRANCH="release-${USER_STORY_ID}"
          
          # Fetch all branches
          git fetch --all

          # Create and push the release branch from main
          git checkout -b $RELEASE_BRANCH origin/main
          git push origin $RELEASE_BRANCH

      - name: Find feature branches
        id: feature-branches
        run: |
          USER_STORY_ID=${{ github.event.inputs['user-story-id'] }}
          
          # Find all feature branches that match the user story ID
          FEATURE_BRANCHES=$(git branch -r | grep "feature/${USER_STORY_ID}" | sed 's/origin\///')
          
          # Set the output for the feature branches
          echo "feature_branches=$FEATURE_BRANCHES" >> $GITHUB_ENV

  create-pull-requests:
    needs: create-release-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create pull requests
        run: |
          USER_STORY_ID=${{ github.event.inputs['user-story-id'] }}
          RELEASE_BRANCH="release-${USER_STORY_ID}"

          # Loop through each feature branch and create a pull request
          for BRANCH_NAME in $FEATURE_BRANCHES; do
            gh pr create --base $RELEASE_BRANCH --head $BRANCH_NAME --title "Merge ${BRANCH_NAME} into ${RELEASE_BRANCH}" --body "Merging changes from ${BRANCH_NAME} to ${RELEASE_BRANCH}"
          done
