name: Send Teams Notification

on:
  pull_request:
    types: [opened, closed]
    branches:
      - sit  # The destination (base) branch must be 'main'
jobs:
  notify_teams:
     runs-on: ubuntu-latest

     steps:
      - name: Send Teams Notification
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        if: startsWith(github.head_ref, 'feature/')
        run: |
          curl -H 'Content-Type: application/json' -d '{
            "title": "GitHub Notification",
            "text": "A new action has been triggered on branch ${{ github.ref_name }}. Event: ${{ github.event_name }}. Action: ${{ github.event.action }}. Status: ${{ job.status }}.",
            "themeColor": "0078D7"
          }' $TEAMS_WEBHOOK_URL
