name: Second Workflow

on:
  repository_dispatch:
    types: [trigger-second-workflow]

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Check Payload
        run: |
          echo "Trigger: ${{ github.event.client_payload.trigger}}"
          echo "The second workflow is successfully triggered."
